# Generated by Django 2.2.3 on 2019-08-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20190807_0918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpenseCategories',
            new_name='ExpenseCategory',
        ),
    ]
