# Generated by Django 2.2.3 on 2019-08-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20190807_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='title',
        ),
        migrations.AlterField(
            model_name='expense',
            name='store',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
