# Generated by Django 2.2.3 on 2019-10-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_storecategorylink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreCategoryLink',
        ),
    ]
